BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBXXXXXBBBBBBBB
BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXX XXX
              XXXX XXXX XXXXX XXX
              XXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                            XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                        XXXXXX
                    BBBBB
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXX

                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                  BBBBB
                XXXXXX
              XXXXXXX
            XXXXXX
XXXXXX
BBBBBBBB