BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBXXXX XXXXBBBBBBBB
BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                	BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
                		XXXXX XXXX XXXXX XXXX
                	BBBB
                		XXXXX XXXX XXXX
                	BBBBB
               	XXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXX XXX
              XXXX XXXX XXXXX XXX
              XXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXX

                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  BBBBB
                XXXXXX
              XXXXXXX
            XXXXXX
XXXXXX
BBBBBBBB