BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBBBXXXX XXXX XXXX XXBBBBBBBB
BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
	XXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXXX
            XXXX
              XXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXX
              XXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX
              XXXXXXXXXXXX
            XXXXX
          XXXXXXXX
          XXXXXXX
            BBB BBBBBBBB BB BBBBBBBBBBB
            	XXXX
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXXXXXXXXXX
                XXXX
                  BB BBBBBBBBBBBBBBB BB BBBB
                    X
                  BBBB
                    
                  BBBBB
                XXXXX
             		XXXX
                  BB BBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXX
                  BBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                  BBBBB
                XXXXX
                XXXX
                  
                XXXXX
                XXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXX
                XXXXX
            	XXXXX
          	BBBBB
          		XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXXXXXX
          	BBBBBB
          XXXXXXXX
        XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXX
    XXXXXX
    XXXX XXXXXX XXX
  XXXXXX
XXXXXX
BBBBBBBB