BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBXXXBBBBBBBB
BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
                    XXX XXXXX XXXXXX XXX
                  BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
                    XXX XXXX XXXX
                  BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXX XXXXXXX
                	BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                    XXX XXXX
                  BBBBB
               	XXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXX XXX
              XXXX XXXX XXXXX XXX
              XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
                    XXXXXX XX XXX XXXXX XXXX XXXXX XXXXX XXXXX
                  BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
                    XXXXXX XX XXX XXXX XXXX XXXX XXXXX XXXXX XXXXX
                  BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXX XX XXX XXXXX XXXXXXXX  XXXX XXXXX XXXXX XXXXX
                  BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                    XXXXXX XX XXX XXXX  XXXX XXXXX XXXXX XXXXX
                  BBBBB
                XXXXXX
                XXXX XXXXXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  BBBBB
                XXXXXX
              XXXXXXX
            XXXXXX
XXXXXX
BBBBBBBB