BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBBBXXXX XXXXXXBBBBBBBB
BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
	XXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXXX
            XXXX
              XXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXX
              XXXXXXXXXXXX
              XXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXX
              XXXXXXXXXXXXXX
            XXXXX
          XXXXXXXX
          XXXXXXX
            BBB BBBBBBB BB BBBBBBBBBBB
            	XXXX
             		XXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BB BBB
                   XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXFFFFFFFFFFFFFFFFXXXX 
                  BBBB
                    FFFFFFFFFFFFFFFF
                  BBBBB
                XXXXX
             		XXXXXXXXX
             		XXXXXXXXX
             		XXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
             		XXXXFFFFFFFFFFFFFFFFFFFFXXXXX
             		XXXXFFFFFFFFFFFXXXXX
             		XXXX
             			BB BBBBBBBBBBBBBB BB BBB
             				XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
             				XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXX
             			BBBB
             				XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
             			BBBBB
                  BB BBBBBBBBBBBBBBBBBBBBBBBBB  BB BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBB BB BBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                  BBBBB
             		XXXXX
            	XXXXX
          	BBBBB
          		XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXXXXXX
          	BBBBBB
          XXXXXXXX
        XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXX
    XXXXXX
    XXXX XXXXXX XXX
  XXXXXX
XXXXXX
BBBBBBBB