BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBXXXX XXXXXXXBBBBBBBB
BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                  XXXX XXXXXXX
                XXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXX XXX
              XXXX XXXX XXXXX XXX
              XXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXX

                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXXX
            XXXXXX
XXXXXX
BBBBBBBB