BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXXXXXXXX XXXXXXX XX XXXXXX XXXXX XXXXXXXXXX
	XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XX
			XXXXXXXX XX
			XXXXXXX XX
			XXXXXXXXXXX XXXXXXXXXXX
		X
		XXXXX
			XXXXXX XXXXXX
			XXXXXXX XXXXXX
			XXXXXXXX XXXXX
			XXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXX XXXXXX
			XXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
			XXXXXX XXXXX
			XXXXXXXXXXXX XXXXXX
			XXXXXXXXXX XXXX
			XXXXXXXX XXXXX
			XXXXXXXXXXX XXXXXXX
		X
		XX
			XXXXXXXXXXXX XXXXXXX
			XXXXXX XXXXX
		X
		XXXXX X
		  XXXXXXXXXX XXXXX
		  XXXXXXXXXXX XXXXX
		X
	XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX
	XXX XXXXXXXXXXXXXXXXXXXX XXXX XXX XXXXXXX XXXXXXX
	XX XXXXXXXXXXXXX
		XXXXXXXXXX XXXXX XXXXXXX XX XXXXXXX XXXXX XXXXXX XXX XX XXXXXX XX XXXX XXXXX XXXXXX XXXX XXXXX XXXX XXXX XX XXXX XXX XXXXXXXXXXXXX XX XXXXXX XXXXX

	XXX XXXXXX XXXXXX XXXXXXXXX XXXXX XXXXX XXXX XX XXXXX XX XXXX XXXXXXXX XXXX 	XXX XX XX XX XXX XXX XXXXXXXXX X XXXXX XXXX XXX XX XXX XX XXXXX

	XXXX
XXXXXXX
XXXXXXX