BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXXXXXXXX XXXXXXX XX XXXXXX XXXXX XXXXXXXXXX
	XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XX
			XXXXXXXX XX
			XXXXXXX XX
			XXXXXXXXXXX XXXXXXXXXXX
		X
		XXXXX
			XXXXXX XXXXXX
			XXXXXXX XXXXXX
			XXXXXXXX XXXXX
			XXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXX XXXXXX
			XXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
			XXXXXX XXXXX
			XXXXXXXXXXXX XXXXXX
			XXXXXXXXXX XXXX
			XXXXXXXX XXXXX
			XXXXXXXXXXX XXXXXXX
		X
		XX
			XXXXXXXXXXXX XXXXXXX
			XXXXXX XXXXX
		X
		XXXXX X
		  XXXXXXXXXX XXXXX
		  XXXXXXXXXXX XXXXX
		X
	XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX
	XXX XXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXX XXXXX XXXXXXX
	XX XXXXXXXXXXXXX
		XXXXXXX XXX XX XXXXXX XXXXX XX XXXXX XXX XX XXXXXX XX XXXXXXXX XXXX XXX XX XXXX XX XXXXXXBBB BBBBBBBXXXXXX XXXXXXX XXXX XXXXX XXX XXXX
	XXXX
XXXXXXX
XXXXXXX