BBBB BBBBBB
BBBB BBBBBBBBB
  XXXX XXXX XXXXXXX XXXXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXX XXXX XXX
    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
           XXXXXXXXXXXXXXX XXXX
      XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX

    XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXX XXXX XXXXX XXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXX
          XXXX XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXX XXX
          XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX
          XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXX XXXX XXX
      XXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXX XXXXX XX XXX XXXXX XXXXX XXX XXXXXXXXX XXXXX
               XXXX XXXXXXXXXXXX XX XXX XXXXX XXXX XXXX XXXXXXX XXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXX BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXBBBBBXX
                XX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXX
                XXX
                  XXXXXXX
                  XX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX
                XXXX
              XXXX
              XXX XXXXXXXXXX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXX BBBBBBBBBBBBB BBBBBBB BBBBBBXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXX
                  XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX BBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBBXX
                    XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX XXXXXXXXX
                  XXXX
                XXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX BBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXX XXXX XXXXXX
                  XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX BBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBBBXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX XXXX XXXXXXXX
                  XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX BBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBBBBBXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX XXXXXXX XXXXXX
                  XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX BBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXX  XXXXX XXXXXXXX XXXX
                  XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX BBBBBBBBBBBBB BBBBBBB BBBBBBBBXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXX XXX XXXXXX
                  XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX BBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXX XXXX XXXXXXXX
                  XXXX
                XXXXX
              XXXXX
            XXXXX
                BBBBB
          BBBBB
          XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX BBBBBBBBBBBBB BBBBBBB BBBBBBBBBXX
              XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXX
                XXXXXXX
                XXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX
            XXXX
          XXXXX
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXX XXX
    XXXXXX
    XXXX XXXXXXXXX XXX
  XXXXXXXX