BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBBBXXXXXX XXXXXXXX XXBBBBBBBB
BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
	XXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXXX
            XXXX
              XXXXXXXXXXXXXX
              XXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXX
            XXXXX
          XXXXXXXX
          XXXXXXX
            BBB BBBBBBB BB BBBBBBBBBBB
            	XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXXXFFFFFFFFFFFXXXXX
            	XXXXX
          	BBBBB
          		XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXXXXXX
          	BBBBBB
          XXXXXXXX
        XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXX
    XXXXXX
    XXXX XXXXXX XXX
  XXXXXX
XXXXXX
BBBBBBBB