BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBXXXXXX XXXXXXXXBBBBBBBB
BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                	BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                		XXXXX XXXX XXXXX XXXXXXXX
                	BBBB
                		XXXXX XXXXX XXXXXXXX
                	BBBBB
               	XXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXX XXX
              XXXX XXXX XXXXX XXX
              XXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXX

                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXXX
            XXXXXX
XXXXXX
BBBBBBBB