BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBBBXXXX XXX XXBBBBBBBB
BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
	XXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXXX
            XXXX
              XXXXXXXXXXXXXX
              XXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXX
            XXXXX
          XXXXXXXX
          XXXXXXX
            BBB BBBBB BB BBBBBBBBBBB
            	XXXX
            		XXXXXXXXX
                	XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX  XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXX XXXXXXXXXXXXX
            	XXXXX
          	BBBBB
          		XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXXXXXX
          	BBBBBB
          XXXXXXXX
        XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXX
    XXXXXX
    XXXX XXXXXX XXX
  XXXXXX
XXXXXX
BBBBBBBB