BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBXXXXBBBBBBBB
BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX  XXXXX
              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                	BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                		XXXXXX XXXX
                	BBBB
                		XXXXX XXXX
                	BBBBB
               	XXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXX XXX
              XXXX XXXX XXXXX XXX
              XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXX

                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  BBBBB
                XXXXXX
              XXXXXXX
            XXXXXX
XXXXXX
BBBBBBBB