BBB BBBB BB BBBBBBBB
	BB BBBBBBBBBBB BB BBBB
		XXXX
			XXXX XXXXXXXXXXXXX
				XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBXX
					
				XXXX
				XXXXX XXXXXXXXXXXXXXXXXXX
			XXXXXX
			BB BBBBBBBBBBBBBBBBB
				XXXX
					BBB B BB BBBBBBBBBBBBBBBBB
						XXXX
							XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBXXXXXX
						XXXXX
					BBBBBB
				XXXXX
			BBBBB
		XXXXX
	BBBBB
BBBBBB