BBBB BBBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
	XXX XXXXXXXXXXXXXXXX XXX XXXX XXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			BBB BBBBBBB BB BBBBBBBBBBB
				BB BBBBBBBBBBBB BB BBBB
					BB BBBBBBBBBBBBBBB B BB
					BBBB
						XXXX XXXXXXXXXXXX
							XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBXX FFFFFFFFFFFFFFFFFFXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXX XX XXXXXXXXXXXXX XXXX XXXXXXXX X  FFFFFFFFFFFXXXXXX
							XXXXXX
						XXXXXX
					BBBBB
				BBBBB
			BBBBB
				XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXXXXXX
			BBBBBB
		XXXXXX			
	XXXXXX
XXXXXXXXXX