BBBB BBBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXX X XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXX XXXXXXXXXXXXX FFFFFFFFFFFXXXXXXXXXXXX				
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			BBB BBBBBBB BB BBBBBBBBBBBBBB
				BB BBBBBBB BB BBBBBBBBBBBBBBBBBBB
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBXX FFFFFFFFFFFFFFFFXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXX X  FFFFFFFFFFFXXXXXX
						XXXXXX
					XXXXXX
				BBBBB
			BBBBB
				XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXXXXXX
			BBBBBB
		XXXXXX			
	XXXXXX
XXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXX XXX XXXX XXXXX XXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXX X XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXX XXXXXXXXXXXXX FFFFFFFFFFFXXXXXXXXXXXX				
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			BBB BBBBBBB BB BBBBBBBBBBB
				BB BBBBBBB BB BBBBBBBBBBBBBBBB
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBXX FFFFFFFFFFFFFFFFXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXX X  FFFFFFFFFFFXXXXXX
						XXXXXX
					XXXXXX
				BBBBB
			BBBBB
				XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXXXXXX
			BBBBBB
		XXXXXX			
	XXXXXX
XXXXXXXXXX
