XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			BBB BBBBBBB BB BBBBBBBBBBB
				BB BBBBBBB BB BBBBBBBBBBBB
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
						XX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXXXX
					XXXXXX
				BBBBB
			BBBBBB
		XXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			BBB BBBBBBB BB BBBBBBBBBBBBBB
				BB BBBBBBB BB BBBBBBBBBBBB
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
						XX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXXXX
					XXXXXX
				BBBBB
			BBBBBB
		XXXXXX
	XXXXXXXXXX