BBBB BBBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXX
		BBB BBBBBBB BB BBBBBBBB
			XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX FFFFFFFFFFFXXXXXX
			XXXXXX
		BBBBBB
	XXXXXX
XXXXXXXXXX