XXXXXXXX XXXXXXXXXXXXXX
	BBB BBBBBBB BB BBBBBBBBBBBBBB
		XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXX	
	BBBBBB	
XXXXXXXXXX