BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBB
BBBB BBBBBBBBBBBB
BBBB BBBBBBBB

BBBBB BBBBBBBBBBBBB
BBBBB BBBB
	BBBBBBB BBBBBBB
	XXXX XXXXXXXXXXXXXXXX
		XXXXXXXX XXXXXXXXXXXXX
			XXX XXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXXXXX X XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXX X  FFFFFFFFFFF
				XXXX XXXXXXXXXXXXXXXXX XXXXX XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXX XX X XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
			XX XXXXXXXXXXXXXXXXXXXXX
				FFFF
				BBBBBBBBBBBBBBB BBBBBB BBBBBBB
				BBBBBBBBBBBBBBBBB
			XXXX
		XXXXXXXXXX
		BBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBB
	XXXXXX	
	BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB
BBBBBBBB