BBBB BBBBBB
BBBB BBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
	XXXXXXXBBBBB BBBBBXXXXXXXXBBBBBBBBXXXXXXXX
XXXXXXX
XXXXXX
	XXXXXXXX
		XXXX X
			XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
			XXXX XXXXXXXXXXXXX
				XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXX
			XXXXXX
			XXX XXXXXXXXXXXX
				XXXX
					XXXX XXXXXXXXXXXXX
						XX XXXXXXBBB BBBBBBBBBBBXX
							XXXX XXXX
						XXXX
					XXXXXX
				XXXXX
				BBBBBBBBBBBBBBB
			XXXXX
			XXXX XXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBXX
					XXXXXX XXXXXXXXXXXXX XXXXXXXXX
					XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXX
						BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
							XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX
								XX XXXXXXXXX XXXXXXXXXXXXX
								XX XXXXXXXXXXXXXXXXX
							XXXX
						BBBB
							XXXX X XXXXX XXXX
							XXXX XXXXXXXXXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXX
								XXXX
								XX XXXXXXBBB BBBBBBBXXXXXX XX XXXX XXXXXXXXXX						
								XX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXX XXXX XXXXXXXXXX						
								XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBXXXXXX X XXXXX XXXX XX XXXXXXXX
								XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBXXXXXX X XXXXX XXXX XXXXXX XX XXXXXXXXXX
							XXXXXX
						BBBBB
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXXXXX
	BBBBB BBBBBBBBBBBB
	XXXXXXXX
        XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX XXXXXXXXX
                    XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX XXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX XXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
        XXXXX
        XXXXXXXXXXX XXXXX XXXXXXXXXX
    XXXXXXXXX
	XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX
XXXXXXX