BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBB
BBBBB BBBBB
	BBBBB BBBBBBBBXXXXXXXXBBBBBBBB
BBBBBBBB

BBBBB BBBB
	BBBBBBBBBBBBBB
	BBBBBBBBBBBB
	XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
		BBBBBBBBBBBBBB
		XXXXXXXX XXXXXXXXXXXXX
			XXX XXXXXXXXXXXXXXBBBBB BBBBBBBBBBBBBBBBBBXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXX
				BBB BBBBBBB BB BBBBBBBBBBB
					XXXX XXXXXXXXXXXX
						XX XXXXXXXXXXXXXXXXXX
						XXXXX
							XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXX
								XX XXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFXXXX						
								XXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX  XXXXXX  FFFFFFFFFFFXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXX XX X XXXXXXXXXXXXXXXXXXX
								XX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXX XXXXXXXX
							XXXXXX
						XXXXXX
					XXXXXX
					XXXX
				BBBBB
					XX XXXXXXXXXXXXXXXXXXXX XXXXXXX
						XXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXX
					XXXX
				BBBBBB
			XXXXXX
			BB BBBBBBBBBBBB
				XXXX XXXXXXXXXXXXXXXXXXX
					BB BBBBBBBBBBBBBBBBB
						XX XXXXXXBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX
					BBBBB
					BB BBBBBBBBBBBBBBBBBBBBB
						XX XXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX
					BBBBB
				XXXXXX
			BBBBB
		XXXXXXXXXX
		BBBBBBBBBBBBB
	XXXXXXXXXX
	BBBBBBBBB
BBBBBBBB